packages:
  - packages/*
  - examples/*
  - apps/*
strictDepBuilds: true
verifyDepsBeforeRun: true
onlyBuiltDependencies:
  - "@tailwindcss/oxide@4.1.17"
  - esbuild@0.25.12
  - esbuild@0.27.0
  - sharp@0.34.5
  - unrs-resolver@1.11.1
